### ISSUE TITLE
Only Department wise report is matching with old system.

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#63]
Only Department Wise Report is not matching with the old system.

Steps to reproduce the issue:

1) Open this on live
([worksuite](https://worksuite.ispusa.net/account/only-department-wise-report))

![Image](https://user-images.githubusercontent.com/13690290/221758797-4beaf241-5214-4e00-a930-195034e6c226.png)

2) Open this on old site:

https://admin.ispusa.net/only_department_wise_report.php?start_date=2022-12-01&end_date=2022-12-31&report_type=3&entity=1

We need both of these reports to be exactly same. Total and details.

**Comment by devs-ik** [comment]
@izshreyansh 
Not a bug [**calculation is correct**], Actually, December 2022 month does not have enough data to compare with old site report. So please try to compare with November 2022, September 2022, or so on months.

I have compared the old site "Only Department Wise Report" with our site "Only Department Wise Report" and I'm unable to find the matching issue with old system.

[worksuite-01-nov-to30-nov-2022-only-department-wise-report.pdf](https://github.com/website-x/worksuite/files/10854431/worksuite-01-nov-to30-nov-2022-only-department-wise-report.pdf)
[oldsite-01-nov-to30-nov-2022-only-department-wise-report.pdf](https://github.com/website-x/worksuite/files/10854432/oldsite-01-nov-to30-nov-2022-only-department-wise-report.pdf)


Please refer to the attached PDFs for more details.
