### ISSUE TITLE
Department Wise Report: Staff Member column is missing

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#64]
DEPARTMENT WISE REPORT

Add staff member column in this report.

Following is a screenshot from their old system. Notice the staff member column

URL: https://worksuite.ispusa.net/account/department-wise-report

![Image](https://user-images.githubusercontent.com/13690290/221868365-e2ecaa6e-cb73-4f9c-8ad1-0de12af9bc23.png)

**Comment by devs-ik** [comment]
@izshreyansh 
Added  Staff Member column and Client column in "Department Wise Report" report and changes deployed on a server.
