### ISSUE TITLE
Find a way to remove duplicate sub diciplines without loosing the data integrity

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#66]
@devs-ik 

Steps to reproduct:

1) go to Department wise report
2) Select these filters:

- 01-11-2022 To 30-11-2022
- Select Department: MEP Department

Notice multiple duplicates in sub dicipline in the report.

We need to figure out the way to remove these duplicates.

**Comment by devs-ik** [comment]
Found the data issue. In 'project_time_logs' table where has different department ID for sub departments.
i.e: Department 'MEP Department' has the following sub departments:
`pID: 46 => Architecture
pID: 50 => Mechanical
pID: 51 => Electrical
pID: 52 => Plumbing
pID: 54 => Fire Protection`

We have the same above names sub departments for other department too and that sub departments **pID** has been stored for 'MEP Department' department in 'project_time_logs' table.

Fixed the issue by using the following code for 'ProjectTimeLog' model in department and only department wise reports.
`->whereHas('subDepartment', function($query) use ($team){
                    return $query->where('department_id', $team->id);
                })`

**Comment by devs-ik** [comment]
@izshreyansh 
Please check the sub departments array with auto incr. ID for department.
array:2 [
      "department_name" => "MEP Department"
      "columns" => array:16 [
        23 => "Mechanical"
        24 => "Electrical"
        25 => "Plumbing"
        27 => "Fire Protection"
        46 => "Architecture"
        50 => "Mechanical"
        51 => "Electrical"
        52 => "Plumbing"
        54 => "Fire Protection"
        68 => "Mechanical"
        70 => "Plumbing"
        108 => "Training-Institute"
        121 => "Electrical"
        150 => "Mechanical"
        151 => "Electrical"
        152 => "Plumbing"
      ]
    ]
    
    
This result is taken from department wise report query.
