### ISSUE TITLE
When user logins the dashboard is slow to load

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#68]
Steps to reproduce:

on https://worksuite.ispusa.net

Login to 

email: brijesha@ispusa.net
password: 123456

A) It takes a lot of time to load. I think this is because of  Monthly Client Work Trends.
We need to optimize this by improving the query.

**Comment by devs-ik** [comment]
Fixed the dashboard load issue.
Solution:
Added foreign key for 'client_id' field of project_time_logs table.
Added index key for 'status' field of users table.
