### ISSUE TITLE
Adjustment in all the charts in the system (Ex: Monthly Client Work Trends) 

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#69]
**NOTICE: We need to do this in all the report that has charts.**

In this chart we need to display all the week and month on y axis. 

Currently we just don't display months for which we don't have data. We need this report like this. 

![Image](https://user-images.githubusercontent.com/13690290/222183207-398bcacf-e399-4a7e-a262-93bbab050709.png)

it's like this in our system:

![Image](https://user-images.githubusercontent.com/13690290/222183762-f49e72a3-df89-4fbe-9d86-c3253646c31c.png)

**Comment by izshreyansh** [comment]
@devs-ik We need to display consistent month or weeks for all charts that are being displayed.

**Comment by izshreyansh** [comment]
@devs-ik We also need to adjust the charts so that all chart's width are same. 
In our system the chart takes very wide width when there is only one bar is shown in the chart.

**Comment by izshreyansh** [comment]
@devs-ik Hi, We need to do this on all the reports where we have implemented charts.

**Comment by devs-ik** [comment]
Display months/weeks for which don't have data for the specific period.
