### ISSUE TITLE
Add missing columns in these reports.

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#70]
Following reports have missing columns in pdf / excel download.

`Client Name, Employee ID, Task Name, Team`

1. Individual
2. Team
3. Department
4. Office
5. Client
6. Sub Discipline
7. Task
8. Only department wise report

Please add those fields in the list of reports above.

Example:

![Image](https://user-images.githubusercontent.com/13690290/222204817-60b48c84-d169-45e7-82d8-64903a827df8.png)

**Comment by devs-ik** [comment]
@izshreyansh 
Added missing columns in the following reports (Excel / PDF / View page for PDF):
1. Client Project Wise Report 
2. Department Wise Report 
3. Only Department Wise Report 
4. Total Hours Report (All Type Of Report)
> Individual
> Team
> Office
> Client
> Sub Discipline
> Task
