### ISSUE TITLE
Preselected time on task complete modal

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#72]
On the task `complete` / `partially complete` modal that you can open from the dashboard.

We have a dropdown for `Hours` & `Minutes`.

Make hour preselected based on the Task Estimate. (Also available in the init timelog entry)

![Image](https://user-images.githubusercontent.com/13690290/223468417-21db2027-c1ae-42bf-b665-12a9b8f2d410.png)

**Comment by devs-ik** [comment]
Added require changes for preselected time.

**Comment by devs-ik** [comment]
Added require changes for preselected time.
