### ISSUE TITLE
Timesheet view bug when editing the task

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#75]
On the [timesheet view](https://worksuite.ispusa.net/account/timesheet-report?start_week=20-03-2023&end_week=26-03-2023)

The second task where the client is `Remington steel metal building`.

When you click on the `Edit Task` button from the timesheet view. 

The client dropdown preselection is incorrect.
See in the following screenshot, The client dropdown should have preselection of `Remington Steel metal building`.

**The client dropdown**
**Estimated hours dropdown.**

Everything seems to be broken and populating incorrect values.

**Comment by izshreyansh** [comment]
This is the task number two on this link: https://worksuite.ispusa.net/account/tasks/63/edit?start_week=20-03-2023&end_week=26-03-2023

If you see, all the values populated are incorrect.

![Image](https://user-images.githubusercontent.com/13690290/223473583-9bd95b32-8ffd-4951-bd2c-abcf1a757f8e.png)

**Comment by izshreyansh** [comment]
https://worksuite.ispusa.net/account/timesheet-report?start_week=20-03-2023&end_week=26-03-2023

![Image](https://user-images.githubusercontent.com/13690290/223473961-f4df2275-140d-4d0f-b6f3-1598b8f8f662.png)

**Comment by devs-ik** [comment]
Fixed the issue and changes pushed in git
