### ISSUE TITLE
Employee is not able to complete the task as it returns 403 error. Same thing happens when he clicks on Pending, Overdue & In Progress, Overdue.

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#77]
@devs-ik Please try to reproduce this issue on the server and figure out what is the problem.

![Image](https://user-images.githubusercontent.com/13690290/224053427-6689e9c2-0afe-4f57-8d95-ccef0d5d9b2a.png)
![Image](https://user-images.githubusercontent.com/13690290/224053426-cec2e38f-e3a3-4768-869b-09f7f06e85eb.png)

**Comment by devs-ik** [comment]
@izshreyansh
This user don't have 'add_timelogs' permission. So it returns 403 error.
