### ISSUE TITLE
Timelogs employee dropdown is not working for Rajni

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#81]
On this link https://worksuite.ispusa.net/account/timelogs

With this user: (rajni@ispusa.net, rajni1297)

The following dropdown for selecting employee is not working

![Image](https://user-images.githubusercontent.com/13690290/224061309-1878e278-b0a2-4faf-9699-beec35e09c9a.png)

**Comment by devs-ik** [comment]
Fix the role permission issue.
