### ISSUE TITLE
Weekly Timesheet total is wrong

### ISSUE THREAD

**Issue by izshreyansh** [website-x/worksuite#82]
Go to this link: https://worksuite.ispusa.net/account/weekly-timesheet

With these credentials: rajni@ispusa.net, rajni1297

The billable hour total here shows 750 hours.
Investigate how is the total so high. 
I couldn't even find the worklogs which amounts to 750 hours.

![Image](https://user-images.githubusercontent.com/13690290/224063125-6edae193-bc59-4629-a360-f3f7bb81e854.png)

**Comment by devs-ik** [comment]
@izshreyansh  It's showing total minutes here.

**Comment by devs-ik** [comment]
Fixed the issue and deployed the changes.
